### ISSUE TITLE
Pieces models

### ISSUE THREAD

**Issue by ybigus** [ybigus/js-chess#1]
Need models for all pieces. Please, commit to src/models fodler

**Comment by netinel** [comment]
@ybigus please check bishop 3d model

**Comment by netinel** [comment]
hi @ybigus check :new: queen 3d model :sunglasses:

**Comment by netinel** [comment]
@ybigus Queen :sunglasses:

**Comment by ybigus** [comment]
@netinel you rock. Only knight is left. Happy new year :)
